(FIG A (CONSISTS-OF P1 P2)
       (RELATIONS (INSIDE P1 P2)))
(FIG B (CONSISTS-OF P3 P4)
      (RELATIONS (INSIDE P3 P2)))
(FIG C (CONSISTS-OF P3 P4)
      (RELATIONS (INSIDE P3 P4)))

(SIM-A_B
          (SIM P2 P4 : (TRANS K 1.0 0 K)))
(SIM-A_C
          (SIM P1 P5 : (TRANS K 1.0 0 K)))

(REMOVE x1 WITH ((INSIDE x1 x2)
                (SIM OB3 x1 (TRANS K 1.0 0 K)))
(ADD x2 ((INSIDE x2 x3)))

(FIG A (CONSISTS-OF P1 P2)
       (RELATIONS (ABOVE P1 P2)))
(FIG B (CONSISTS-OF P3))
(FIG C (CONSISTS-OF P4 P5)
      (RELATIONS (ABOVE P4 P5)))

(SIM-A_B ())
(SIM-A_C
          (SIM P1 P4 : (TRANS K 1.0 0 K)))

(REMOVE x1 WITH ((ABOVE x1 x2)
                (SIM OB3 x1 (TRANS K 1.0 0 K)))
(REMOVE x2 WITH ((ABOVE x3 x2)
                (SIM OB3 x1 (TRANS K 1.0 0 K)))
(ADD x3 ())


(FIG A (CONSISTS-OF P1 P2 P3)
       (RELATIONS (ABOVE P1 P2)(ABOVE P2 P3))
       (PATTERN (STRIPE P1)(DOT P2)(PLAIN P3))

(FIG A (CONSISTS-OF P4 P5 P6)
      (RELATIONS (ABOVE P4 P5)(ABOVE P5 P6))
      (PATTERN (PLAIN P1)(STRIPE P2)(DOT P3))

(FIG A (CONSISTS-OF P7 P8 P9)
      (RELATIONS (ABOVE P7 P8)(ABOVE P8 P9))
      (PATTERN (DOT P1)(STRIPE P2)(PLAIN P3))
